---
- name:
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Add disk and USB 3.0 controllers for virtual machine located by name
    community.vmware.vmware_guest_controller:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      controllers:
      - bus_sharing: noSharing # noSharing(default), pysicalSharing, virtualSharing
        state: present # required
        controller_number: 1
        type: paravirtual # required # buslogic, lsilogic, lsilogicsas, paravirtual, sata, nvme, usb2, usb3
      validate_certs: no # yes(default), no
    register: disk_controller_facts
