---
- name:
  hosts: localhost
  gather_facts: no
  tasks:
  - name: gather scsi controller facts 
    community.vmware.vmware_guest_controller:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vm_datacenter }}"
      name: "{{ vm_name }}"
      folder: "{{ vm_folder }}"
      gather_disk_controller_facts: yes # no(default), yes
      validate_certs: no # yes(default), no
    delegate_to: localhost
    register: disk_controller_facts

  - name: Add scsi controller if scsi controller 1 is not existed
    community.vmware.vmware_guest_controller:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      #datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      controllers:
      - bus_sharing: noSharing # noSharing(default), pysicalSharing, virtualSharing
        state: present # required
        controller_number: 1
        type: paravirtual # required # buslogic, lsilogic, lsilogicsas, paravirtual, sata, nvme, usb2, usb3
      validate_certs: no # yes(default), no
    when: disk_controller_facts.disk_controller_data.scsi['1'] is not defined
