---
- name:
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Add disks to virtual machine using UUID
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      disk:
        - size_gb: "{{ vm_disk_size }}" # or size: 10gb
          type: eagerzeroedthick
          state: present
          datastore: "{{ datastore }}"
          bus_sharing: noSharing
          scsi_controller: "{{ vm_scsi_controller }}"
          unit_number: "{{ vm_unit_number }}"
          sharing: yes
          disk_mode: 'independent_persistent'
      validate_certs: no
    delegate_to: localhost
    register: disk_facts
