---
- name:
  hosts: localhost
  gather_facts: no
  tasks:
  - name: 
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      disk:
        - state: absent
          scsi_controller: "{{ vm_scsi_controller }}"
          unit_number: "{{ vm_unit_number }}"
      validate_certs: no
    delegate_to: localhost
    register: disk_facts
